---
name: Check
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Install bun
        uses: oven-sh/bun-install@v1

      - name: Setup | Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run | Lint
        run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Install bun
        uses: oven-sh/bun-install@v1

      - name: Setup | Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run | Type Check
        run: bun run typecheck
